Added support for Apple Silicon
bazelbuild/bazelisk pull request #272
Opened 2021-10-06 16:38 UTC by linzhp

Bazelish should check the Bazel version. If it is greater or equal to than 4.1, add support for arm64 so we can run Bazel on Apple Sillicon. Fixed #270

2021-10-06 18:30 UTC, mindaugasrukas commented
LGTM. Works on my M1 machine.

2022-01-30 02:02 UTC, linzhp commented
ping @philwo

2022-02-01 13:18 UTC, philwo approved these changes
Thank you!

2022-02-01 13:21 UTC, philwo submitted a review, later dismissed
Sorry, found two little things to change - could you have a look?

2022-02-01 13:21 UTC, philwo commented on bazelisk.py
> +            # Apple Sillicon was supported since 4.1:
nit: s/Sillicon/Silicon/

2022-03-01 18:34 UTC, linzhp commented
@fweikert I believe the current CI errors are transient issues. It can be fixed by restarting the job, but I don't have the permission to do so.

2022-03-01 18:47 UTC, fweikert requested changes

2022-03-01 18:47 UTC, fweikert commented on bazelisk.py
> +        # It works becasue all recent commits of Bazel supports arm64 on Darwin and Linux.
typo

2022-03-01 18:47 UTC, fweikert commented on bazelisk.py
> +        # It works becasue all recent commits of Bazel supports arm64 on Darwin and Linux.
support

2022-03-01 18:47 UTC, fweikert commented on bazelisk.py
> +    operating_system = get_operating_system()
please move this block into its own function

2022-03-02 15:21 UTC, linzhp commented
@fweikert addressed your comments. All tests passed.

2022-03-02 17:34 UTC, merged