Download native macOS arm64 binary on M1
bazelbuild/bazelisk pull request #303
Opened 2022-02-22 21:21 UTC by codeman9

When using macOS on M1 and downloading a commit or any keyword that resolves to a commit (e.g., `last_green`) `bazelisk` was downloading from the url: `https://storage.googleapis.com/bazel-builds/artifacts/macos/[commit]/bazel`.

This PR changes the url to be of the form: `https://storage.googleapis.com/bazel-builds/artifacts/macos_arm64/[commit]/bazel`.

Also, to get tests to now pass on M1, `test.sh` has been updated to insert the arch determined from `uname -m` for the versions that support `arm64`.

2022-05-17 08:58 UTC, meteorcloudy requested changes

2022-05-17 08:58 UTC, meteorcloudy commented on platforms/platforms.go
> +	if platform == "macos" && arch == "arm64" {
We publish binaries for `windows_arm64`, can we add the support here?

2022-06-03 14:22 UTC, fweikert commented on platforms/platforms.go
> +		platform = platform + "_arm64"
Good question - I think we have added too many things over time. We should refactor the entire platform support (with arm64 in mind).

2022-06-15 12:13 UTC, meteorcloudy approved these changes

2022-06-15 12:13 UTC, meteorcloudy commented on platforms/platforms.go
> +		platform = platform + "_arm64"
OK, I tested on a Linux ARM64 machine, downloading a Bazel binary at a certain commit never worked. So this change isn't make anything worse.

2022-06-15 12:13 UTC, merged

2022-06-15 12:13 UTC, meteorcloudy commented
@fweikert Can you make an new release for Bazelisk?

2022-06-15 16:39 UTC, fweikert commented
Will do